config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: redirect('/users/sign_in')
  
patch 'recipes/:id/update_public', to: 'recipes#update_public', as: 'recipe_update_public'
get '/public_recipes', to: 'public_recipes#index', as: 'public_recipes'


resources :recipes, only: [:index, :show, :create, :new, :destroy], path: 'recipes' do
  patch :update_public, on: :member
end

  resources :foods, only: [:index, :create, :new, :destroy], path: 'foods'
  resources :recipe_foods, only: [ :create, :new, :destroy], path: 'recipe_foods'
  end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new # guest user (not logged in)
    if user.owner?
      can :manage, Recipe, user_id: user.id
      can :manage, FOOD, user_id: user.id
    else
      can :read, :all
    end
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :recipe_foods, foreign_key: :food_id
  belongs_to :user

  validates :name, presence: true, length: { maximum: 250 }
  validates :user_id, presence: true
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0 }
  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/recipe.rb
class Recipe < ApplicationRecord
  has_many :recipe_foods, foreign_key: :recipe_id
  belongs_to :user

  validates :name, presence: true, length: { maximum: 250 }
  validates :description, presence: true, length: { maximum: 400 }
  validates :cooking_time, presence: true, length: { maximum: 250 }
  validates :preparation_time, presence: true, length: { maximum: 250 }
  validates :user_id, presence: true
end

app/models/recipe_food.rb
class RecipeFood < ApplicationRecord
  belongs_to :recipe, foreign_key: :recipe_id
  belongs_to :food, foreign_key: :food_id

  validates :quantity, presence: true, numericality: { greater_than_or_equal_to: 0 }
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :foods, foreign_key: :user_id
  has_many :recipes, foreign_key: :user_id

  validates :name, presence: true, length: { maximum: 250 }

  def owner?(recipe_id)
    recipes.exists?(id: recipe_id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :configure_permitted_parameters, if: :devise_controller?

  protected

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    devise_parameter_sanitizer.permit(:account_update, keys: [:name])
  end

  def after_sign_in_path_for(_resource)
    '/foods'
  end

  # # Catch all CanCan errors and alert the user of the exception
  rescue_from CanCan::AccessDenied do |exception|
    redirect_to root_url, alert: exception.message
  end
end

app/controllers/foods_controller.rb
class FoodsController < ApplicationController
  def index
    @foods = current_user.foods
  end

  def new
    @food = Food.new
  end

  def create
    @food = Food.new(food_params)
    @food.user_id = current_user.id

    if @food.save
      flash[:notice] = 'Food Added successfully!'
      redirect_to '/foods'
    else
      flash[:alert] = "Couln't Add Food Please Try Again!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @food = current_user.foods.find(params[:id])

    if @food&.destroy
      flash[:success] = 'Food deleted!'
    else
      flash[:danger] = 'Sorry Failed To Delete Food!'
    end
    redirect_to request.referrer
  end

  private

  def food_params
    params.require(:food).permit(:name, :measurement_unit, :price, :quantity)
  end
end

app/controllers/public_recipes_controller.rb
class PublicRecipesController < ApplicationController
  def index
    @public_recipes = Recipe.where(public: true).includes(recipe_foods: [:food], user: {}).order(created_at: :desc)
  end
end

app/controllers/recipe_foods_controller.rb
class RecipeFoodsController < ApplicationController
  def new
    @recipe = Recipe.find(params[:recipe_id])
    @foods = Food.all
    @recipe_food = RecipeFood.new
  end

  def create
    recipe_id = params[:recipe_id]
    foods = params[:add_food] || []
    quantities = params[:quantity] || []

    foods.each_with_index do |food_id, _index|
      quantity = quantities[food_id.to_s].to_i

      # Check if a recipe_food record already exists with the same recipe_id and food_id
      @recipe_food = RecipeFood.find_or_initialize_by(recipe_id:, food_id:)

      # If the record already exists, update its quantity attribute
      if @recipe_food.persisted?
        @recipe_food.update(quantity: @recipe_food.quantity + quantity)
      else
        # Otherwise, create a new recipe_food record with the given attributes
        @recipe_food.quantity = quantity

        if @recipe_food.save
          flash[:notice] = 'Recipe added successfully!'
        else
          flash[:alert] = "Couldn't add recipe. Please try again."
          render :new, status: :unprocessable_entity
        end
      end
    end

    redirect_to "/recipes/#{recipe_id}"
  end

  def destroy
    @recipe_food = RecipeFood.includes(:food).find_by(id: params[:id], recipe_id: params[:recipe_id])

    if @recipe_food&.destroy
      flash[:success] = 'ingredient Removed!'
    else
      flash[:danger] = 'Sorry Failed To Remove Ingredient!'
    end
    redirect_to request.referrer
  end
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  def index
    @recipes = current_user.recipes
  end

  def show
    @ingredients = RecipeFood.includes(:food).where(recipe_id: params[:id])
    @recipe = Recipe.find(params[:id])
  end

  def new
    @recipe = Recipe.new
  end

  def update_public
    @recipe = Recipe.find(params[:id])

    if @recipe.update(public: params[:recipe][:public] == '1')
      flash[:notice] = 'Recipe is now Public'
    else
      flash[:danger] = 'Sorry Failed To make Recipe Public!'
    end

    redirect_to request.referrer
  end

  def create
    preparation_time_number = params[:recipe][:preparation_time_number]
    preparation_time_unit = params[:recipe][:preparation_time_unit]

    cooking_time_number = params[:recipe][:cooking_time_number]
    cooking_time_unit = params[:recipe][:cooking_time_unit]

    preparation_time = "#{preparation_time_number} #{preparation_time_unit}"
    cooking_time = "#{cooking_time_number} #{cooking_time_unit}"

    @recipe = Recipe.new(recipe_params)
    @recipe.preparation_time = preparation_time
    @recipe.cooking_time = cooking_time
    @recipe.user_id = current_user.id

    if @recipe.save

      flash[:notice] = 'Recipe Added Successfully!'
      redirect_to '/recipes'
    else
      flash[:alert] = "Couln't Add Recipe Please Try Again!"
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @recipe = current_user.recipes.find(params[:id])

    if @recipe&.destroy
      flash[:success] = 'Recipe Removed!'
    else
      flash[:danger] = 'Sorry Failed To Remove Recipe!'
    end
    redirect_to request.referrer
  end

  private

  def recipe_params
    params.require(:recipe).permit(:name, :preparation_time, :cooking_time, :description)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/food_helper.rb
module FoodHelper
end

app/helpers/public_recipes_helper.rb
module PublicRecipesHelper
end

app/helpers/recipe_foods_helper.rb
module RecipeFoodsHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/foods/_food.html.erb
<div id="<%= dom_id food %>">
  <p>
    <strong>Name:</strong>
    <%= food.name %>
  </p>

  <p>
    <strong>Measurement unit:</strong>
    <%= food.measurement_unit %>
  </p>

  <p>
    <strong>Price:</strong>
    <%= food.price %>
  </p>

  <p>
    <strong>Quantity:</strong>
    <%= food.quantity %>
  </p>

  <p>
    <strong>User:</strong>
    <%= food.user_id %>
  </p>

</div>

app/views/foods/index.html.erb
<section id="food-list">
  <h1 class="text-center fw-bold">Welcome To Your Food Store</h1>
  <br>
  <br>
  <div class="text-center">
    <button class="btn btn-success">
      <%= link_to 'Add food', new_food_path, class: "text-white text-decoration-none" %>
    </button>
  </div>
  <br>
  <br>
  <table class="table table-striped table-bordered  w-75 mx-auto shadow">
    <thead class="thead-dark fs-5">
      <tr>
        <th>Index</th>
        <th>Food</th>
        <th>Measurement Unit</th>
        <th>Quantity</th>
        <th>Unit price</th>
        <th>Actions</th>
      </tr>
    </thead>
    <tbody>
      <% @foods.each_with_index do |food, index| %>
        <tr>
          <td><%= index + 1 %></td>
          <td><%= food.name %></td>
          <td><%= food.measurement_unit %></td>
          <td><%= food.quantity %></td>
          <td><%= number_to_currency(food.price) %></td>
          <td>
            <%= button_to "Delete", food_path(food), method: :delete, data: { confirm: "Are you sure you want to delete this food?" }, class: "btn btn-danger btn-sm" %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/foods/new.html.erb
<div class=" shadow col-6 h-600 mx-auto rounded border border-darker px-10 py-5">
  <h1 class="text-center fw-bold">Add Food</h1>
  </br>
  <%= form_with model: @food, url: foods_path, local: true, class: "form" do |form| %>
    <div class="col-md-8 mb-3 mx-auto">
      <%= form.label :name ,class: "form-label" %>
    <%= form.text_field :name, required: true, class: "form-control"  %>
  </div>
  <div class="col-md-8 mb-3 mx-auto">
    <%= form.label :measurement_unit ,class: "form-label" %></br>
  <%= form.select :measurement_unit, ['grams', 'ounces', 'cups', 'tablespoons', 'teaspoons','pounds', 'kilos'], {}, { required: true, class:"form-select form-control rounded border"  } %>
</div>
<div class="col-md-8 mb-3 mx-auto">
  <%= form.label :unit_price ,class: "form-label" %></br>
<%= form.text_field :price, required: true, class: "form-control"  %>
</div>
<div class="col-md-8 mb-3 mx-auto">
  <%= form.label :quantity ,class: "form-label" %></br>
<%= form.text_field :quantity, required: true, class: "form-control"  %>
</div>
<div class="col-md-8 mb-3 mx-auto">
  <%= form.submit "Add", class:"btn btn-primary" %>
  <button class="btn btn-light">
    <%=link_to 'cancel', '/foods'  %>
  </button>
</div>
<% end %>
</div>

app/views/foods/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @food %>

<div>
  <%= link_to "Back to foods", foods_path %>

  <%= button_to "Destroy this food", @food, method: :delete %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Project</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-KK94CHFLLe+nY2dmCWGMq91rCGa5gtU4mk92HdvYe+M/SXH301p5ILy+dN9+nJOZ" crossorigin="anonymous">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
      <div class="container-fluid">
        <a class="navbar-brand" href="/foods">Le Recipe</a>
        <div class="d-flex justify-content-between">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0 mx-5">
            <% if current_user %>
              <li class="nav-item">
                <%= link_to "Foods", '/foods', class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "My Recipes", '/recipes', class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Public Recipes", '/public_recipes', class: "nav-link" %>
              </li>
              <li class="nav-item">
                <%= link_to "Shopping List", '', class: "nav-link" %>
              </li>
            <% end %>
          </ul>
          
        </div>
        <br>
          <% if current_user %>
            <div class="d-flex align-items-center">
              <p class="fs-6">Logged In: <Span class="font-weight-bold"><%= current_user.name %></Span></p>
              <%= button_to "Sign Out", destroy_user_session_path, method: :delete, class: "nav-link mx-5" %>
            </div>
          <% end %>
      </div>
    </nav>
    <br>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>
  </body>
</html>

app/views/public_recipes/index.html.erb
<section id="public-list">
  <h1 class="text-center fw-bold">Public Recipes</h1>
  <br>
  <% @public_recipes.each_with_index do |recipe, index| %>
    <div class="d-flex justify-content-between rounded shadow p-5 border-dark  w-75 mx-auto">
      <div>
        <%= link_to recipe_path(recipe.id), class:"text-decoration-none" do %>
          <h3 ><%= recipe.name%></h3>
        <% end %>
        <br>
        <h5 class="title"><%= "By: #{ recipe.user.name}" %></h5>
      </div>
      <div class="public-resipe-div">
        <p class="fs-6"><strong>Total food items:</strong> <%= recipe.recipe_foods.count %></p>
        <p class="fs-6"><strong>Total price:</strong> $<%= recipe.recipe_foods.sum { |item| item.food.price * item.quantity } %></p>
      </div>
    </div>
    <br>
  <% end %>
</section>

app/views/recipe_foods/new.html.erb
<h1 class="text-center fw-bold">Add Ingredients</h1>
<br>
<br>
<%= form_tag recipe_foods_path, method: :post do %>
  <%= hidden_field_tag :recipe_id, @recipe.id %>
  <table class="table table-striped table-bordered  w-75 mx-auto shadow">
    <thead class="thead-dark fs-5">
      <tr >
        <th>index</th>
        <th>Food</th>
        <th>Quantity</th>
        <th>Add</th>
      </tr>
    </thead>
    <tbody>
      <% current_user.foods.each_with_index do |food, index| %>
        <tr>
          <td class="fs-10" ><%= index+1 %></td>
          <td class="fs-10"><%= food.name %></td>
          <td><%= number_field_tag "quantity[#{food.id}]", nil, class: "col-md-2 fs-10" %></td>
          <td ><input class=" form-check-input-lg" type="checkbox" name="add_food[]" value="<%= food.id %>"></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <br>
  <div class="col-md-2 mb-3 mx-auto">
  <%= submit_tag "save", class:"btn btn-primary"  %>

  </div>
<% end %>

app/views/recipes/index.html.erb
<section id="recipe-list">
  <h1 class="text-center fw-bold">Your Recipe Catalogue</h1>
<br>
<br>
<div class="text-center">
 <button class="btn btn-success ">
    <%= link_to "New Recipe", new_recipe_path, class:"text-white text-decoration-none" %>
  </button>
</div>
<br>
 
  <% @recipes.each_with_index do |recipe, index| %>
    <div class="d-flex justify-content-between rounded shadow p-5 border-dark  w-75 mx-auto">
      <div>
        <%= link_to recipe_path(recipe.id),class: "text-decoration-none" do %>
          <h3 class="title"><%= recipe.name %></h3>
        <% end %>
        <br>
        <% if current_user.owner? recipe%>
          <%= button_to "Delete", recipe_path(recipe), method: :delete, data: { confirm: "Are you sure you want to delete this food?" }, class:"btn btn-danger" %>
        <% end %>
      </div>
      <div class="unit-1">
        <p class="desc"><%= recipe.description %></p>
      </div>
    </div>
    <br>
  <% end %>
</section>

app/views/recipes/new.html.erb
<div class=" shadow col-6 h-600 mx-auto rounded border border-darker px-10 py-5">
  <h1 class="text-center fw-bold">Add Recipe</h1>
  <br>
  <%= form_with model: @recipe, url: recipes_path, local: true, class: "form mx-auto" do |form| %>
    <div class="col-sm-10 mb-3 mx-auto">
      <%= form.label :name ,class: "form-label form-label" %></br>
    <%= form.text_field :name, required: true, class: "form-control", placeholder: "recipe name" %>
  </div>
  <br>
  <div class="row justify-content-center mb-3">
    <%= form.label :preparation_time, class: " text-center form-label" %>
    <div class="col-sm-5">
      <%= form.text_field :preparation_time_number, required: true, class: "form-control", placeholder: "number"%>
    </div>
    <div class="col-sm-5 ">
      <%= form.select :preparation_time_unit, ['hour(s)', 'minute(s)'], { prompt: "hr / min" }, { required: true, class: "form-control"  } %>
    </div>
  </div>
  <br>
  <div class="row justify-content-center mb-3">
    <%= form.label :cooking_time, class: "text-center form-label" %>
    <div class="col-sm-5">
      <%= form.text_field :cooking_time_number, required: true, class: "form-control", placeholder: "number"%>
    </div>
    <div class="col-sm-5">
      <%= form.select :cooking_time_unit, ['hour(s)', 'minute(s)'], { prompt: "hr / min" }, { required: true, class: "form-control"  } %>
    </div>
  </div>
  <br>
  <div class="col-sm-10 mb-3 mx-auto">
    <%= form.label :description, class: "form-label" %>
    <%= form.text_area :description, required: true, class: "form-control" %>
  </div>
  <br>
  <div class="row col-md-2 mb-3 mx-auto">
    <%= form.submit "Add", class:"btn btn-primary" %>
    <button class="btn btn-light">
      <%=link_to 'cancel', '/recipes' %>
    </button>
  </div>
<% end %>
</div>

app/views/recipes/show.html.erb
<section id="recipe_details">
  <h1 class="text-center fw-bold"><%=@recipe.name%></h1>
  <br>
  <br>
  <div class="d-flex w-75 mx-auto justify-content-between">
    <p class="fs-5">Preparation time: <%= @recipe.preparation_time %></p>
    <% if current_user.owner? @recipe %>
      <div class="form-check form-switch mx-5">
        <%= form_for @recipe, url: recipe_update_public_path(@recipe), remote: true do |f| %>
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <%= f.check_box :public, class:"form-check-input form-check-success", onchange: 'this.form.submit();' %>
          <label class="fs-5 fw-bold" for="public">Public:</label>
        <% end %>
      </div>
    <% end %>
  </div>
  <div class="w-75 mx-auto">
    <p class=" fs-5">Cooking time: <%= @recipe.cooking_time %></p>
    <p class="fs-5">Steps:</p>
    <p class="fs-5"><%= @recipe.description %></p>
  </div>
  <br>
  <div class="d-flex justify-content-center">
    <button class="btn btn-light btn-lg mx-5" >Generate shopping list</button>
    <% if current_user.owner? @recipe || @recipe.public === true%>
      <button class="btn btn-success btn-lg mx-5" >
        <%= link_to 'Add ingredient', new_recipe_food_path(recipe_id: @recipe.id),  class: "text-white text-decoration-none"  %>
      </button>
    <% end %>
  </div>
  <br>
  <hr>
  <br>
  <div >
    <table class="table table-striped table-bordered  w-75 mx-auto shadow">
      <thead class="thead-dark fs-5">
        <tr>
          <th>Index</th>
          <th>Food</th>
          <th>Quantity</th>
          <th>Value</th>
          <th>Action</th>
        </tr>
      </thead>
      <tbody>
        <% @ingredients.each_with_index do |ingredient, index| %>
          <tr>
            <td><%= index + 1 %></td>
            <td><%= ingredient.food.name %></td>
            <td><%= ingredient.quantity %></td>
            <td><%= number_to_currency(ingredient.quantity * ingredient.food.price) %></td>
            <td>
              <% if current_user.owner? @recipe%>
                <%= button_to "Remove", recipe_food_path(recipe_id: @recipe.id, id: ingredient.id), method: :delete, data: { confirm: "Are you sure you want to delete this recipe food?" },class: "text-white text-decoration-none btn btn-danger btn-sm"   %>
              <% end %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>